require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'date'
require './lib/enigma'
require './lib/generator'
require 'mocha/minitest'
require './lib/crypt'
require './lib/messages'
